if (process.env.NODE_ENV !== 'production') {
    require('dotenv').config();
}
const PORT = process.env.PORT || 3000;
const cors = require('cors');
const express = require("express");
const app = express();

const mongoose = require('mongoose');
const listing = require('./models/testingModel.js')
const Movies = require("./models/movieModel.js")
const Shows = require('./models/showModel.js')
const Users = require('./models/userModel.js')
const Theater =require('./models/theaterModel.js')
const theaterRoute = require('./routes/theaterRoute');
const bcrypt = require('bcryptjs');
const { notFound, errorHandler } = require('./middlewares/errorMiddleware');
//const { addTheater, getAllTheaters } = require('../controllers/theaterController');
const movieRoutes=require('./routes/moviesRoutes.js')
const showRoutes=require('./routes/showRoutes.js')
const userRoutes = require('./routes/userRoutes');
const bookingRoutes=require('./routes/bookingRoutes.js')
const MongoStore = require('connect-mongo'); //  CORRECT//for store session on cloud
//const PORTpassport = require('passport');
//const dbUrl='mongodb://127.0.0.1:27017/myshow'
//const methodOverride = require('method-override');\
const mongodbUrl=process.env.MONGODB_URI
const morgan = require('morgan');
app.use(cors({
  origin: [
    'http://localhost:5173',
    'https://bookmyshow-frontend-mzylsvdih-daksh-8269.vercel.app',
    /\.vercel\.app$/ // 👈 Accepts any preview/production URL generated by Vercel
  ],
  credentials: true
}));
app.use(express.json());

app.disable('etag'); // 👈 Disables 304 caching so fresh data is always sent!
async function main() {
    //for local db connection await mongoose.connect('mongodb://127.0.0.1:27017/airbnb');
    //   await mongoose.connect(dbUrl)
    await mongoose.connect(mongodbUrl);

    console.log('MongoDB connected');
}
main().catch(err => console.log(err));
app.get('/', (req, res) => {
    res.redirect("/listing/movies");
});



app.use((req, res, next) => {
    console.log(`Incoming Request: ${req.method} ${req.url}`);
    next();
});
app.use(morgan('dev'));

// Base path for all authentication requests
app.use('/listing/users', userRoutes);
app.use('/listing/movies', movieRoutes);
app.use('/listing/booking',bookingRoutes)
app.use('/listing/shows',showRoutes)
app.use('/listing/theaters', theaterRoute);
//--------------------------------------------------------------

app.listen(PORT, () => {
  console.log(`Server running on port ${PORT}`);
});


// 3. 404 Handler (if no route matched above)
app.use(notFound);

// 4. Global Error Handler (to catch server crashes)
app.use(errorHandler);

// At the bottom of server.js, after all other routes
app.get('/listing', (req, res) => {
    res.status(200).send({
        success: true,
        message: "Welcome to the BookMyShow API",
        version: "1.0.0",
        status: "Running"
    });
});
